services:
  mysql:
    image: "mysql"
    container_name: "mysql_appointment_service"
    environment:
      MYSQL_DATABASE: appointment_service
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql