spring:
  application:
        name: customer_service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  datasource:
    url: "jdbc:mysql://localhost:3309/customer_service"
    username: root
    password: root


server:
  servlet:
    context-path: /api/v1
  port: 8084
