services:
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      -  ./database/mysql:/var/lib/mysql
