services:
    mysql:
      image: "mysql:latest"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=customer_service
      ports:
        - "3309:3306"
      volumes:
        - ./database/mysql:/var/lib/mysql