spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: appointment_service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/appointment/**

          - id: customer_service
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/customer/**

server:
  port: 8888
