

spring:
  application:
    name: identity_service

  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8801
  servlet:
    context-path: /api/v1/identity